name: build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build --stacktrace

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lenemon-build
          path: build/libs/